name: devbin

services:
  devbin_frontend:
    build:
      context: frontend/.
    ports:
      - "3000:3000"
    env_file:
      - .env
    profiles: ["dev_frontend"]

  devbin:
    env_file:
      - .env
    build:
      context: backend/.
    ports:
      - "8000:8000"
    volumes:
      - ./files:/app/files
    depends_on:
      devbin_db:
        condition: service_healthy
    profiles: ["dev_backend"]

  devbin_db:
    env_file:
      - .env
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
