services:
  devbin_test_db:
    image: postgres:16
    container_name: devbin_test_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devbin_test
    ports:
      - "5433:5432"  # Use different port to avoid conflicts
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - devbin_test_data:/var/lib/postgresql/data

volumes:
  devbin_test_data:
