[project]
name = "backend"
version = "0.1.0"
description = "DevBins backend"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.124",
    "uvicorn[standard]>=0.30",
    "dependency-injector>=4.41",
    "SQLAlchemy>=2.0",
    "asyncpg>=0.29",
    "pydantic>=2.7",
    "pydantic-settings>=2.12.0",
    "uuid>=1.30",
    "aiofiles>=25.1.0",
    "setuptools>=68",
    "wheel>=0.45.1",
    "alembic>=1.17.2",
    "slowapi>=0.1.9",
    "orjson>=3.11.5",
    "aiocache>=0.12.3",
    "fastapi-cors>=0.0.6",
    "ruff>=0.14.9",
    "basedpyright>=1.36.1",
]
[project.optional-dependencies]
migrations = [
    "psycopg2-binary",
]

[tool.uvicorn]
factory = false

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages]
find = { where = ["."], include = ["app*", "files*", "alembic*"] }

[tool.pyright]
include = ["app", "main.py"]
exclude = ["tests", "venv", ".venv"]
reportMissingImports = true
reportMissingTypeStubs = false
reportAny = false
reportUnknownMember = false
reportUnknownVariableType = false
reportUnknownMemberType = false
reportArgumentType = false
reportCallIssue = false
reportUnusedCallResult = false
pythonVersion = "3.13"
executionEnvironments = [
    { root = ".", pythonVersion = "3.13" }
]
