[project]
name = "backend"
version = "0.1.0"
description = "DevBins backend"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.124",
    "uvicorn[standard]>=0.30",
    "dependency-injector>=4.41",
    "SQLAlchemy>=2.0",
    "asyncpg>=0.29",
    "pydantic>=2.7",
    "pydantic-settings>=2.12.0",
    "uuid>=1.30",
    "aiofiles>=25.1.0",
    "setuptools>=68",
    "wheel>=0.45.1",
    "alembic>=1.17.2",
    "slowapi>=0.1.9",
    "orjson>=3.11.5",
]
[project.optional-dependencies]
migrations = [
    "psycopg2-binary",
]

[tool.uvicorn]
factory = false

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages]
find = { where = ["."], include = ["app*", "files*", "alembic*"] }
